// AUTOGENERATED, DO NOT EDIT.
// This file was created by PPDS.

// This file contains definitions generated by DECLARE statements.


#undef X_assert
#undef X_PUSH
#undef X_POP
#undef X_AT
#undef X_assert_fail

#undef Y_assert
#undef Y_PUSH
#undef Y_POP
#undef Y_AT
#undef Y_assert_fail

