/* AUTOGENERATED, DO NOT EDIT. */
/* This file was created by PPDS. */

/* This file contains definitions generated by DECLARE statements.*/


#undef X_WRAP
#undef X_assert_fail
#undef X_assert_in_bounds
#undef X

