/* AUTOGENERATED, DO NOT EDIT. */
/* This file was created by PPDS. */

/* This file contains definitions generated by DECLARE statements.*/


///////////////////////////////////
// FDASD HIER KORRIGIEREN!!!, VERWEIS AUF HEADER-SOURCEW
// FROM: file: tests/full_examples/should_pass/main.c, line 12
///////////////////////////////////


#undef X_WRAP
#undef X_assert_with_index
#undef X_assert_fail_with_index
#undef X_assert_in_bounds
#undef X

