/* AUTOGENERATED, DO NOT EDIT. */
/* This file was created by PPDS. */

/* This file contains definitions generated by DECLARE statements.*/


///////////////////////////////////
// FROM: file: tests/full_examples/should_pass/main.c, line 12
///////////////////////////////////


// public:

#define X(i, j) x[X_assert_in_bounds(i,j,#i,#j), X_WRAP_Dim0(i)*ny + X_WRAP_Dim1(j)]

// internal:



#if 0 // numpy_wraparound
#define X_WRAP_Dim0(i) (i < 0 ? (nx+ i) : i)
#else // numpy_wraparound
#define X_WRAP_Dim0(i) i
#endif // numpy_wraparound

#if 0 // skip_checks

#define X_assert_in_bounds_of_Dim0(i, expr_name) ((void)0)

#else // skip_checks

#   if 0 // numpy_wraparound

#define X_assert_in_bounds_of_Dim0(i, expr_name) ((((i) >= nx) || ((i) < -(nx))) ? X_assert_fail(i, expr_name, nx, "Dim0") : ((void)0))

#   else // numpy_wraparound

#define X_assert_in_bounds_of_Dim0(i, expr_name) ((((i) >= nx) || ((i) < 0) )? X_assert_fail(i, expr_name, nx, "Dim0") : ((void)0))

// #define X_assert_in_bounds_of_Dim0(i, expr_name) do{(if((((i) >= nx) || ((i) < 0) ) { X_assert_fail(i, expr_name, nx, "Dim0") } }while(0)

#   endif // numpy_wraparound

#endif //skip_checks




#if 0 // numpy_wraparound
#define X_WRAP_Dim1(i) (i < 0 ? (ny+ i) : i)
#else // numpy_wraparound
#define X_WRAP_Dim1(i) i
#endif // numpy_wraparound

#if 0 // skip_checks

#define X_assert_in_bounds_of_Dim1(i, expr_name) ((void)0)

#else // skip_checks

#   if 0 // numpy_wraparound

#define X_assert_in_bounds_of_Dim1(i, expr_name) ((((i) >= ny) || ((i) < -(ny))) ? X_assert_fail(i, expr_name, ny, "Dim1") : ((void)0))

#   else // numpy_wraparound

#define X_assert_in_bounds_of_Dim1(i, expr_name) ((((i) >= ny) || ((i) < 0) )? X_assert_fail(i, expr_name, ny, "Dim1") : ((void)0))

// #define X_assert_in_bounds_of_Dim1(i, expr_name) do{(if((((i) >= ny) || ((i) < 0) ) { X_assert_fail(i, expr_name, ny, "Dim1") } }while(0)

#   endif // numpy_wraparound

#endif //skip_checks






#define X_assert_fail(index_val, index_expr, dim_size, dim_name) \
	fprintf(stderr,"\n\n----> ppds ASSERTION FAILURE: INDEX OUT OF BOUNDS <----\n"),\
  fprintf(stderr,"index " index_expr " (="), PRINT(index_val),\
  fprintf(stderr,") is out of bounds for axis " dim_name " of size "), PRINT(dim_size), fprintf(stderr, "="), PRINT(dim_size),\
  fprintf(stderr, "  (numpy_wraparound is 0).\n"),\
	fprintf(stderr,"\ndetected in line %d, function %s, file %s\n",__LINE__,__func__,__FILE__),\
	fprintf(stderr, "with the object X declared in file: tests/full_examples/should_pass/main.c, line 12 of type ARR2D\n"),\
  fprintf(stderr, " calling panic action: exit(1)\n"),\
  exit(1)



#define X_assert_in_bounds(i,j,i_string,j_string) X_assert_in_bounds_of_Dim0(i,i_string), X_assert_in_bounds_of_Dim1(j,j_string)


