/* AUTOGENERATED, DO NOT EDIT. */
/* This file was created by PPDS. */

/* This file contains definitions generated by DECLARE statements.*/


// public:
#define X(i) x[X_assert_in_bounds(i,#i), X_WRAP(i)]

// internal:
#if 0
#define X_WRAP(i) (i < 0 ? (n + i) : i
#else
#define X_WRAP(i) i
#endif

#if NDEBUG
#define X_assert_in_bounds(i, expr_name) ((void)0)
#else

#   if 0

#define X_assert_in_bounds(i, expr_name) ((((i) >= n) || ((i) < -(n))) ? X_assert_fail(i, expr_name) : ((void)0))

#   else //numpy_wraparound

#define X_assert_in_bounds(i, expr_name) ((((i) >= n) || ((i) < 0) )? X_assert_fail(i, expr_name) : ((void)0))

#   endif //numpywraparound

#endif //skip_checks

#define X_assert_fail(i, expr_name) \
	fprintf(stderr,"\n\n----> ppds ASSERTION FAILURE: index of 1D-Array is OUT OF BOUNDS <----\n"),\
  fprintf(stderr,"index (" expr_name "is out of bounds for ARR1D of size "), PRINT(n),\
  fprintf(stderr, "numpywraparound is 0.\n"),\
	fprintf(stderr,"\ndetected in line %d, function %s, file %s\n",__LINE__,__func__,__FILE__),\
	fprintf(stderr, "with the object X declared in file: tests/full_examples/custom_panic_works/main.c, line 20 of type ARR1D\n"),\
	fprintf(stderr, "object X defined by: pointer=x, len=n numpy_wraparound=0\n"),\
	fprintf(stderr, "values of X:\n"), PRINT(x), PRINT(n),\
  PRINT_ARR(x, n),\
  fprintf(stderr, " calling panic action: error=1\n"),\
  error=1


