// AUTOGENERATED, DO NOT EDIT.
// This file was created by PPDS.

// This file contains definitions generated by DECLARE statements.


#undef X_assert_with_index
#undef X_assert_fail_with_index
#undef X_assert_in_bounds
#undef X

